"""Standalone Theseus E24 Survivor Lab package."""
__version__ = "0.2.0"
from .classification import ClassificationDecision, classify_survivor
from .beliefs import BeliefState, HypothesisBelief, initial_belief_state
from .experiments import ExperimentDefinition, ExperimentKind, ExperimentScore, default_experiment_catalog, expected_information_gain, rank_experiments
from .investigator import ActiveInvestigator, ExperimentExecutor, ExperimentObservation, InvestigationResult, InvestigationStep
from .learning import LearnedExperimentPolicy, LearningActiveInvestigator, LearningInvestigationRun, investigation_signature, trajectory_from_result
from .self_play import (
    InvestigationAttempt,
    MutationChallenge,
    PolicyBenchmarkSummary,
    PromotionCriteria,
    PromotionDecision,
    SelfPlayEpisode,
    SelfPlayLeague,
    TestCandidate,
    VerificationOutcome,
    evaluate_policy_promotion,
    run_self_play_episode,
)
from .context import build_survivor_causal_context, extract_causal_context
from .contracts import (
    AnalysisFinding,
    CausalContext,
    SurvivorCausalContext,
    DependencyEvidence,
    EnvironmentEvidence,
    ExecutionEvidence,
    ExecutionStatus,
    GenerationSource,
    MutantEvidence,
    MutantStatus,
    ProviderMetadata,
    RepairHypothesis,
    RequestedMode,
    SelectionEvidence,
    SourceEvidence,
    SurvivorAnalysisRequest,
    SurvivorAnalysisResult,
    SurvivorCategory,
    SurvivorClassification,
    TestEvidence,
    TestFragment,
    TestProposal,
    ValidationPlan,
    ValidationStep,
)
from .providers import (
    DeterministicTemplateProvider,
    NullRepairProposalProvider,
    ProviderRequest,
    ProviderResponse,
    ProviderSuggestion,
    RepairProposalProvider,
    provider_response_from_dict,
    provider_response_to_dict,
)
from .serialization import package_resource_bytes, package_resource_json, package_resource_text
from .service import SurvivorAnalysisService, analyze_request
from .validation import canonical_relative_path, canonical_text, canonical_utc_timestamp, semantic_text_sha256
__all__ = [
    "LearningInvestigationRun",
    "LearningActiveInvestigator",
    "run_self_play_episode",
    "evaluate_policy_promotion",
    "VerificationOutcome",
    "TestCandidate",
    "SelfPlayLeague",
    "SelfPlayEpisode",
    "PromotionDecision",
    "PromotionCriteria",
    "PolicyBenchmarkSummary",
    "MutationChallenge",
    "InvestigationAttempt",
    "trajectory_from_result",
    "investigation_signature",
    "LearnedExperimentPolicy",
    "InvestigationStep",
    "InvestigationResult",
    "ExperimentObservation",
    "ExperimentExecutor",
    "ActiveInvestigator",
    "rank_experiments",
    "expected_information_gain",
    "default_experiment_catalog",
    "ExperimentScore",
    "ExperimentKind",
    "ExperimentDefinition",
    "initial_belief_state",
    "HypothesisBelief",
    "BeliefState",
    "AnalysisFinding",
    "CausalContext",
    "ClassificationDecision",
    "DependencyEvidence",
    "DeterministicTemplateProvider",
    "EnvironmentEvidence",
    "ExecutionEvidence",
    "ExecutionStatus",
    "GenerationSource",
    "MutantEvidence",
    "MutantStatus",
    "NullRepairProposalProvider",
    "ProviderRequest",
    "ProviderMetadata",
    "ProviderResponse",
    "ProviderSuggestion",
    "RepairHypothesis",
    "RequestedMode",
    "RepairProposalProvider",
    "SelectionEvidence",
    "SourceEvidence",
    "SurvivorAnalysisRequest",
    "SurvivorAnalysisResult",
    "SurvivorAnalysisService",
    "SurvivorCategory",
    "SurvivorClassification",
    "TestEvidence",
    "TestFragment",
    "TestProposal",
    "ValidationPlan",
    "ValidationStep",
    "SurvivorCausalContext",
    "build_survivor_causal_context",
    "canonical_relative_path",
    "canonical_text",
    "canonical_utc_timestamp",
    "package_resource_bytes",
    "package_resource_json",
    "package_resource_text",
    "provider_response_from_dict",
    "provider_response_to_dict",
    "semantic_text_sha256",
    "analyze_request",
    "classify_survivor",
    "extract_causal_context",
]
