"""Stable enum values shared by Theseus, Gallifrey and the engine."""
from __future__ import annotations
from enum import Enum
class CampaignStatus(str, Enum):
    """Lifecycle states visible outside the execution engine."""
    CREATED = "created"
    PREPARING = "preparing"
    RUNNING = "running"
    CANCELLING = "cancelling"
    CANCELLED = "cancelled"
    COMPLETE = "complete"
    PARTIAL = "partial"
    FAILED = "failed"
    RECOVERED = "recovered"
class CampaignMode(str, Enum):
    """User-visible campaign intent, independent from worker mechanics."""
    STANDARD = "standard"
    DISCOVERY = "discovery"
    AUDIT = "audit"
class WorkerStatus(str, Enum):
    """Portable worker lease states."""
    LEASED = "leased"
    STARTING = "starting"
    RUNNING = "running"
    RETRYING = "retrying"
    COMPLETE = "complete"
    ERROR = "error"
    CANCEL_REQUESTED = "cancel_requested"
    CANCELLED = "cancelled"
    ORPHANED = "orphaned"
class ArtifactRetentionClass(str, Enum):
    """Evidence retention policy, not a filesystem implementation detail."""
    EPHEMERAL = "ephemeral"
    CAMPAIGN = "campaign"
    FOREVER = "forever"
class EngineEventType(str, Enum):
    """Known engine events; readers still preserve unknown string event types."""
    CAMPAIGN_PREPARATION_STARTED = "campaign_preparation_started"
    COLLECTION_COMPLETED = "collection_completed"
    INDEX_COMPLETED = "index_completed"
    BASELINE_STARTED = "baseline_started"
    BASELINE_COMPLETED = "baseline_completed"
    MUTANTS_DISCOVERED = "mutants_discovered"
    PLAN_CREATED = "plan_created"
    SHARD_STARTED = "shard_started"
    MUTANT_STARTED = "mutant_started"
    TEST_LEVEL_STARTED = "test_level_started"
    TEST_LEVEL_COMPLETED = "test_level_completed"
    MUTANT_COMPLETED = "mutant_completed"
    SHARD_COMPLETED = "shard_completed"
    REPORT_MATERIALIZED = "report_materialized"
    ENGINE_WARNING = "engine_warning"
    ENGINE_ERROR = "engine_error"
class StatisticsEventType(str, Enum):
    """Canonical append-only event names consumed by the statistics projection."""
    TEST_STARTED = "test.started"
    TEST_COMPLETED = "test.completed"
    MUTANT_STARTED = "mutant.started"
    MUTANT_COMPLETED = "mutant.completed"
    SELECTION_ESCALATED = "selection.escalated"
    EXECUTION_TIMEOUT = "execution.timeout"
    INFRASTRUCTURE_FAILED = "infrastructure.failed"
    REUSE_DECIDED = "reuse.decided"
    PLAN_DECIDED = "plan.decided"
    RECOVERY_PERFORMED = "recovery.performed"
    WORKER_STARTED = "worker.started"
    WORKER_HEARTBEAT = "worker.heartbeat"
    WORKER_STOPPED = "worker.stopped"
    PROCESS_STARTED = "process.started"
    PROCESS_STOPPED = "process.stopped"
def enum_value(value: str | Enum) -> str:
    # Normalize known enum instances and future string event types to one wire value.
    return str(value.value if isinstance(value, Enum) else value)
