"""Canonical statistics events, append-only ingestion and incremental read models."""
from .events import JsonlStatisticsEventSink, MemoryStatisticsEventSink, StatisticsEventSink
from .projections import (
    STATISTICS_DURATION_SAMPLE_SIZE,
    STATISTICS_PROJECTION_MAX_BATCH,
    STATISTICS_PROJECTION_MAX_LIMIT,
    STATISTICS_PROJECTION_SCHEMA_VERSION,
    StatisticsProjectionCheckpoint,
    StatisticsProjectionCursor,
    StatisticsProjectionError,
    StatisticsProjectionResult,
    StatisticsProjectionStore,
    StatisticsSummary,
    StatisticsSummaryPage,
)
from .store import (
    STATISTICS_INGEST_MAX_RECORDS,
    STATISTICS_QUERY_MAX_LIMIT,
    STATISTICS_STORE_SCHEMA_VERSION,
    StatisticsEventConflictError,
    StatisticsEventCursor,
    StatisticsEventPage,
    StatisticsEventStore,
    StatisticsIngestionError,
    StatisticsIngestionResult,
    StatisticsStoreError,
    StoredStatisticsEvent,
)
from .planning import (
    PLANNER_DECISION_PRODUCER_ID,
    plan_decision_events_from_outbox,
    plan_decision_statistics_events,
    project_plan_decision_outbox,
)
__all__ = [
    "PLANNER_DECISION_PRODUCER_ID",
    "STATISTICS_DURATION_SAMPLE_SIZE",
    "STATISTICS_INGEST_MAX_RECORDS",
    "STATISTICS_PROJECTION_MAX_BATCH",
    "STATISTICS_PROJECTION_MAX_LIMIT",
    "STATISTICS_PROJECTION_SCHEMA_VERSION",
    "STATISTICS_QUERY_MAX_LIMIT",
    "STATISTICS_STORE_SCHEMA_VERSION",
    "JsonlStatisticsEventSink",
    "MemoryStatisticsEventSink",
    "StatisticsEventConflictError",
    "StatisticsEventCursor",
    "StatisticsEventPage",
    "StatisticsEventSink",
    "StatisticsEventStore",
    "StatisticsIngestionError",
    "StatisticsIngestionResult",
    "StatisticsProjectionCheckpoint",
    "StatisticsProjectionCursor",
    "StatisticsProjectionError",
    "StatisticsProjectionResult",
    "StatisticsProjectionStore",
    "StatisticsStoreError",
    "StatisticsSummary",
    "StatisticsSummaryPage",
    "plan_decision_events_from_outbox",
    "plan_decision_statistics_events",
    "project_plan_decision_outbox",
    "StoredStatisticsEvent",
]
