"""Performance measurement contracts and durable regression authority."""
from .warm_executor import CertifiedExecutionResult, CertifiedWarmExecutor, WarmExecutionKey, WarmExecutionTrustStore, WarmTrustState
from .concurrency import AutoConcurrencyDecision, ConcurrencySample, choose_auto_workers
from .tuning import ProjectPerformanceSample, ProjectTuningStore
from .accounting import TimelineAccounting, reconcile_exclusive_timeline, reconcile_nested_timeline
from .authority import (
    PERFORMANCE_AGGREGATION_VERSION,
    PERFORMANCE_AUTHORITY_VERSION,
    PERFORMANCE_MIN_REPETITIONS,
    PERFORMANCE_QUERY_MAX_LIMIT,
    PERFORMANCE_SCHEMA_VERSION,
    STANDARD_METRICS,
    STANDARD_PHASES,
    PerformanceAuthorityError,
    PerformanceCollector,
    PerformanceConflictError,
    PerformanceMetric,
    PerformanceMetricSummary,
    PerformanceRepetitionSummary,
    PerformanceRun,
    PerformanceStore,
    PhaseMeasurement,
    InvariantFinding,
    OptimizationGateReport,
    RegressionBudget,
    RegressionFinding,
    RegressionReport,
    WorkloadIdentity,
    evaluate_optimization_gate,
    evaluate_phase_accounting,
    performance_run_from_benchmark_report,
    summarize_performance_runs,
    performance_run_from_runner_report,
)

__all__ = [
    "WarmTrustState",
    "WarmExecutionTrustStore",
    "WarmExecutionKey",
    "CertifiedWarmExecutor",
    "CertifiedExecutionResult",
    "ProjectTuningStore",
    "ProjectPerformanceSample",
    "choose_auto_workers",
    "ConcurrencySample",
    "AutoConcurrencyDecision",
    "reconcile_nested_timeline",
    "reconcile_exclusive_timeline",
    "TimelineAccounting",
    "PERFORMANCE_AGGREGATION_VERSION",
    "PERFORMANCE_AUTHORITY_VERSION",
    "PERFORMANCE_MIN_REPETITIONS",
    "PERFORMANCE_QUERY_MAX_LIMIT",
    "PERFORMANCE_SCHEMA_VERSION",
    "STANDARD_METRICS",
    "STANDARD_PHASES",
    "PerformanceAuthorityError",
    "PerformanceCollector",
    "PerformanceConflictError",
    "PerformanceMetric",
    "PerformanceMetricSummary",
    "PerformanceRepetitionSummary",
    "PerformanceRun",
    "PerformanceStore",
    "PhaseMeasurement",
    "InvariantFinding",
    "OptimizationGateReport",
    "RegressionBudget",
    "RegressionFinding",
    "RegressionReport",
    "WorkloadIdentity",
    "evaluate_optimization_gate",
    "evaluate_phase_accounting",
    "performance_run_from_benchmark_report",
    "performance_run_from_runner_report",
    "summarize_performance_runs",
]
